<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutonomousFleet.Services.Order.Domain\AutonomousFleet.Services.Order.Domain.csproj" />
    <ProjectReference Include="..\AutonomousFleet.Services.Order.Application\AutonomousFleet.Services.Order.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
